CREATE TABLE citas(
    id VARCHAR(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    texto VARCHAR (500) NOT NULL,
    user_id INT(11) NOT NULL,
    autor VARCHAR(50) NOT NULL DEFAULT 'Anónimo',
    FOREING KEY (user_id) REFERENCES users (id)
)